import type { Metadata } from "next";
import { cookies } from "next/headers";
import { getCart } from "@/src/api/getCart";
import { CartProvider } from "@/src/components/atom/cartProvider/CartProvider";
import Providers from "@/src/components/atom/providers/Providers";
import Navbar from "@/src/components/molecules/navbar/Navbar";
import "@/src/styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Flavio Shop",
    default: "Flavio Shop Cart",
  },
  description: "Generated by create next app",
};

export default async function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();

  const userId = cookieStore.get("user_id")?.value || "1";

  const cart = await getCart(Number(userId));

  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar />
          <CartProvider initialCart={cart}>{children}</CartProvider>
        </Providers>
      </body>
    </html>
  );
}
