import type { Metadata } from "next";
import { getCart } from "@/src/api/getCart";
import { CartProvider } from "@/src/components/atom/cartProvider/CartProvider";

export const metadata: Metadata = {
  title: {
    template: "Flavio Shop",
    default: "Cart",
  },
  description: "Generated by create next app",
};

export default async function CartLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cart = await getCart();

  return <CartProvider initialCart={cart}>{children}</CartProvider>;
}
