import type { Metadata } from "next";
import { getCart } from "../api/getCart";
import Providers from "@/src/components/atom/providers/Providers";
import Navbar from "@/src/components/molecules/navbar/Navbar";
import "@/src/styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Flavio Shop",
    default: "Flavio Shop",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { items } = await getCart();
  const itemsCount = items?.reduce((acc, item) => acc + item.quantity, 0) || 0;

  return (
    <html lang="en">
      <body>
        <Navbar cartItemsCount={itemsCount} />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
