import type { Metadata } from "next";
import Navbar from "@/src/components/molecules/navbar/Navbar";
import "@/src/styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Flavio Shop",
    default: "Flavio Shop",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
