import type { Metadata } from "next";
import { cookies } from "next/headers";
import React from "react";
import { getCategories } from "@/src/api/getCategories";
import { getProducts } from "@/src/api/getProducts";
import { ProductsProvider } from "@/src/components/atom/productsProvider/ProductsProvider";
import { getFiltersFromCookie } from "@/src/utils/getFiltersFromCoockie";

export const metadata: Metadata = {
  title: {
    template: "%s | Flavio Shop",
    default: " Products",
  },
  description: "Generated by create next app",
};

export default async function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();
  const filtersString = cookieStore.get("shop_filters")?.value;
  const { category, sortBy, order, limit, skip } =
    getFiltersFromCookie(filtersString);

  const [initialProducts, categories] = await Promise.all([
    getProducts({
      category,
      sortBy,
      order,
      limit,
      skip,
    }),
    getCategories(),
  ]);

  return (
    <ProductsProvider initialData={initialProducts} categories={categories}>
      {children}
    </ProductsProvider>
  );
}
