import type { Metadata } from "next";
import { cookies } from "next/headers";
import { getCategories } from "@/src/api/getCategories";
import { getProducts } from "@/src/api/getProducts";
import { ProductsProvider } from "@/src/components/atom/productsProvider/ProductsProvider";
import "@/src/styles/global.css";

export const metadata: Metadata = {
  title: {
    template: "%s | Flavio Shop",
    default: "Flavio Shop Products",
  },
  description: "Generated by create next app",
};

export default async function ShopLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = await cookies();

  const category = cookieStore.get("preferred_category")?.value || "";
  const sortBy = cookieStore.get("preferred_sortBy")?.value || "";
  const order = cookieStore.get("preferred_order")?.value || "";
  const limit = Number(cookieStore.get("preferred_limit")?.value) || 10;
  const page = Number(cookieStore.get("current_page")?.value) || 1;
  const skip = (page - 1) * limit;

  const [initialProducts, categories] = await Promise.all([
    getProducts({
      category,
      sortBy,
      order,
      limit,
      skip,
    }),
    getCategories(),
  ]);

  return (
    <html lang="en">
      <body>
        <ProductsProvider initialData={initialProducts} categories={categories}>
          {children}
        </ProductsProvider>
      </body>
    </html>
  );
}
